### ISSUE TITLE
cati and FD examples

### ISSUE THREAD

**Issue by apportela** [adrientaudiere/cati#5]
Dear Adrien,

Congratulations on the great package.
Would you consider releasing a tutorial or some short examples on the use of cati with FD in the near future?
Despite the examples avalaible I am still finding it difficult to implement FD functions in ComIndex and ComIndexMulti.

Thank you in advance,

**Comment by adrientaudiere** [comment]
Sorry Apportela, I am no longer in research professional activities, so I have no time to release other tutorial.
