### ISSUE TITLE
Error in decompCTRE

### ISSUE THREAD

**Issue by diogoprov** [adrientaudiere/cati#6]
Hi,

I'm running into an error that seems to have happened when I updated R to v 4.3.2. Here's my `sessionInfo`: 

```
> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.4.1
```

When I try to run `decompCTRE` 

```
decomp_within <- decompCTRE(traits = morpho_sjc, formula = ~1, 
+                             ind.plot = pocas_sjc,
+            sp = species_sjc, 
+            printprogress = TRUE)
```

I get the following error:

```
Error in (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) : 
  'length = 2' in coercion to 'logical(1)'
```

This seems to have been caused by the way R now handles `if` clauses, as reported in the News file below:

<img width="1587" alt="Captura de Tela 2024-03-27 às 16 16 48" src="https://github.com/adrientaudiere/cati/assets/5214836/9ed5807a-4f34-4c0d-bce2-a462063f793a">

Do you perhaps could take a look at this function and update it?

Thank you

**Comment by diogoprov** [comment]
I got the same message in R 4.2.3

```
> sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 14.4.1
```

but they came as warnings, not an error.

```
Warning messages:
1: In (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
2: In (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
3: In (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
4: In (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
5: In (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
6: In (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
7: In (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
8: In (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
```

**Comment by adrientaudiere** [comment]
Hi @diogoprov, this bug was resolved in issue 406d64b72b0bafe9b897c633d62cba3088e46620, but I still haven't submitted this version to CRAN. You can use the development version using:

```r
devtools::install_github("adrientaudiere/cati/pkg/cati")
```

**Comment by diogoprov** [comment]
Merci beaucoup, Adrien! 

But I got thir error when I tried to install the package from GitHub

```
Downloading GitHub repo adrientaudiere/cati@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/adrientaudiere/cati/tarball/HEAD' failed
```

Have you seen too that the example that uses the `hypervolume` in the help of `ComIndexMulti` due to changes in the syntax of `hypervolume`?

Marci aussi

**Comment by adrientaudiere** [comment]
I don't understand the error you get. The download address work fine for me.
You can try the function `devtools::install_local()` on the zip files of the cati repositories.

Thanks for the bug on `hypervolume` example. I will fix it soon. I will submit a new version to cran in a couple of weeks.

**Comment by diogoprov** [comment]
Now it worked! 

Merci again!

**Comment by eshelman-s** [comment]
Hi ,

I am also having issues installing from the github using `devtools::install_github("adrientaudiere/cati/pkg/cati")`. I keep getting the error:
 `devtools::install_github("adrientaudiere/cati/pkg/cati")
Downloading GitHub repo adrientaudiere/cati@HEAD
Error: Failed to install 'cati' from GitHub:
  input string 217 is invalid
In addition: Warning message:
In gsub("[^/]", "", file_list) :
  unable to translate 'adrientaudiere-cati-b03e632/In progress/FDchange modifi+<ae>.R' to a wide string`

 Additionally when I use `devtools::install_local()` on the zip files of the cati repositories I get the error 
`devtools::install_local("./packages/cati-master.zip")
Error: Failed to install 'cati-master.zip' from local:
  Does not appear to be an R package (no DESCRIPTION)`.

Do you have any suggestions? I want to use the decompCTRE function but obviously need to use the updated, not CRAN version atm.

Thanks

**Comment by adrientaudiere** [comment]
hi @eshelman-s,
The cati package is in a subdirectory of the github folder. You must try `devtools::install_local("cati-master/pkg/cati/")` after unzip.
But you might encounter the same problem as with the solution `devtools::install_github()`.

So I also add an **Encoding** field to DESCRIPTION file. Please let me know if it works now!

**Comment by leandromenezess** [comment]
Hi,

A few months ago I ran the Tstats function and it worked fine in this same script. However, I'm currently having trouble with this function and also with extracting the p value using the Pval function.

The following error appears when running the functions:

>   morpho_T <- values_morpho %>% dplyr::select(crc, perna, larg_cab, comp_cab)
>   species <- as.factor(values_morpho$especie)
>   pocas <- as.factor(values_morpho$local)

>   res.poca <- Tstats(morpho_T, ind.plot = pocas, sp = species, nperm = 9, print = FALSE)

>   plot(res.poca)
**Error in if (class(obs) == "list") { : the condition has length > 1**

>   Pval(res.poca, na.rm = TRUE)
**Error in if (class(obs) == "list") { : the condition has length > 1**

Do you know what might be happening? Thank you!
