### ISSUE TITLE
Error in Tstats and Pval

### ISSUE THREAD

**Issue by leandromenezess** [adrientaudiere/cati#7]
Hi,

A few months ago I ran the Tstats function and it worked fine in this same script. However, I'm currently having trouble with this function and also with extracting the p value using the Pval function.

The following error appears when running the functions:

morpho_T <- values_morpho %>% dplyr::select(crc, perna, larg_cab, comp_cab)
species <- as.factor(values_morpho$especie)
pocas <- as.factor(values_morpho$local)

res.poca <- Tstats(morpho_T, ind.plot = pocas, sp = species, nperm = 9, print = FALSE)

plot(res.poca)
Error in if (class(obs) == "list") { : the condition has length > 1

Pval(res.poca, na.rm = TRUE)
Error in if (class(obs) == "list") { : the condition has length > 1

Do you know what might be happening? Thank you!

**Comment by adrientaudiere** [comment]
Hi @leandromenezess,

It seems that the line [3358](https://github.com/adrientaudiere/cati/blob/75d20f1a1fec1c59afc2dc36b0da397129cc9835/pkg/cati/R/allfunctions_cati.R#L3358) is involved. 

Did you try to run the example of plot.Tstat on your installation ? For me it works.

```r
data(finch.ind)
	
## Not run: 
	res.finch <- Tstats(traits.finch, ind.plot = ind.plot.finch, 
	sp = sp.finch, nperm = 9, print = FALSE)
	
	res.finch

	#Tstats class is associated to S3 methods plot, barplot and summary
	
	plot(res.finch)
```

If it works, please send me a simplified version of your data.
