### ISSUE TITLE
error in cati::decompCTRE

### ISSUE THREAD

**Issue by ingolfkuehn** [adrientaudiere/cati#8]
Dear Adrien,

I would like to run the decompCTRE function, but get the following error:

```r
data(finch.ind)
res.decomp <- decompCTRE(traits = traits.finch, sp = sp.finch,
                          ind.plot = ind.plot.finch, print = FALSE)
```
Error in (dim(res.1) != dim(res.2)) || (dim(res.1) != dim(res.3)) :
  'length = 2' in coercion to 'logical(1)'

I use a MacBook Pro with MacOS 14.6.1, R version 4.4.2 (2024-10-31) and cati version 0.99.4

Best wishes
Ingolf

**Comment by adrientaudiere** [comment]
Thanks for the report @ingolfkuehn.

I think I fix the bug in the new development version (0.99.5) thanks to commit fbf862261df08bccc484b2b7d2ab7e285d72ff44. 

Install the new version with the command above and let me know if you have any further problems.  

```r
devtools::install_github("adrientaudiere/cati")
```

**Comment by ingolfkuehn** [comment]
Thank you very much, Adrien. It works perfectly now :-)
